In [1]:
# Import the numpy and pandas packages     
import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [2]:
# Write your code for importing the csv file here
#import pandas as pd
movies = pd.read_csv('Movie+Assignment+Data.csv')
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [3]:
# Write your code for inspection here
movies.info()
movies.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [4]:
movies.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [5]:
movies.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [7]:
# Write your code for column-wise null count here
null_counts = movies.isnull().sum()
print("column-wise null counts:")
print(null_counts)

column-wise null counts:
color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [8]:
# Write your code for row-wise null count here
null_counts_per_row = movies.isnull().sum(axis=1)
print("row-wise null counts:")
print(null_counts_per_row)

row-wise null counts:
0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [9]:
# Write your code for column-wise null percentages here
null_percentage = (movies.isnull().mean())* 100
print("column-wise null_percentage")
print(null_percentage)

column-wise null_percentage
color                         0.376760
director_name                 2.062265
num_critic_for_reviews        0.991473
duration                      0.297442
director_facebook_likes       2.062265
actor_3_facebook_likes        0.456078
actor_2_name                  0.257783
actor_1_facebook_likes        0.138806
gross                        17.529248
genres                        0.000000
actor_1_name                  0.138806
movie_title                   0.000000
num_voted_users               0.000000
cast_total_facebook_likes     0.000000
actor_3_name                  0.456078
facenumber_in_poster          0.257783
plot_keywords                 3.033908
movie_imdb_link               0.000000
num_user_for_reviews          0.416419
language                      0.277613
country                       0.099147
content_rating                6.008328
budget                        9.756098
title_year                    2.141582
actor_2_facebook_likes        0.257783
imdb_score                    0.000000
aspect_ratio                  6.523895
movie_facebook_likes          0.000000
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [10]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
column_to_drop = ['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords']
print('column that drop from movies data frame: ',column_to_drop) 
movies.drop(labels=['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords'],axis=1)

column that drop from movies data frame:  ['color', 'director_facebook_likes', 'actor_1_facebook_likes', 'actor_2_facebook_likes', 'actor_2_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name', 'cast_total_facebook_likes', 'actor_3_name', 'duration', 'facenumber_in_poster', 'content_rating', 'country', 'movie_imdb_link', 'aspect_ratio', 'plot_keywords']

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [11]:
# Write your code for dropping the rows here
movies1 = movies.dropna(axis=0,how='any',subset =('gross','budget','content_rating','aspect_ratio'))
movies1

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [12]:
# Write your code for dropping the rows here

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [13]:
# Write your code for filling the NaN values in the 'language' column here
movies1['language'].replace('NaN','English')
movies1

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [14]:
movies1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3784 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      3782 non-null   object
 1   director_name              3784 non-null   object
 2   num_critic_for_reviews     3783 non-null   float64
 3   duration                   3784 non-null   float64
 4   director_facebook_likes    3784 non-null   float64
 5   actor_3_facebook_likes     3779 non-null   float64
 6   actor_2_name               3783 non-null   object
 7   actor_1_facebook_likes     3784 non-null   float64
 8   gross                      3784 non-null   float64
 9   genres                     3784 non-null   object
 10  actor_1_name               3784 non-null   object
 11  movie_title                3784 non-null   object
 12  num_voted_users            3784 non-null   int64
 13  cast_total_facebook_likes  3784 non-null   int64
 14  actor_3_name               3779 non-null   object
 15  facenumber_in_poster       3778 non-null   float64
 16  plot_keywords              3769 non-null   object
 17  movie_imdb_link            3784 non-null   object
 18  num_user_for_reviews       3784 non-null   float64
 19  language                   3782 non-null   object
 20  country                    3784 non-null   object
 21  content_rating             3784 non-null   object
 22  budget                     3784 non-null   float64
 23  title_year                 3784 non-null   float64
 24  actor_2_facebook_likes     3783 non-null   float64
 25  imdb_score                 3784 non-null   float64
 26  aspect_ratio               3784 non-null   float64
 27  movie_facebook_likes       3784 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 857.3+ KB

In [15]:
# Write your code for checking number of retained rows here
null_counts = movies1.isnull().sum()
null_percentage = movies1.isnull().mean()*100
print("column-wise null counts:")
print(null_counts,null_percentage)

column-wise null counts:
color                         2
director_name                 0
num_critic_for_reviews        1
duration                      0
director_facebook_likes       0
actor_3_facebook_likes        5
actor_2_name                  1
actor_1_facebook_likes        0
gross                         0
genres                        0
actor_1_name                  0
movie_title                   0
num_voted_users               0
cast_total_facebook_likes     0
actor_3_name                  5
facenumber_in_poster          6
plot_keywords                15
movie_imdb_link               0
num_user_for_reviews          0
language                      2
country                       0
content_rating                0
budget                        0
title_year                    0
actor_2_facebook_likes        1
imdb_score                    0
aspect_ratio                  0
movie_facebook_likes          0
dtype: int64 color                        0.052854
director_name                0.000000
num_critic_for_reviews       0.026427
duration                     0.000000
director_facebook_likes      0.000000
actor_3_facebook_likes       0.132135
actor_2_name                 0.026427
actor_1_facebook_likes       0.000000
gross                        0.000000
genres                       0.000000
actor_1_name                 0.000000
movie_title                  0.000000
num_voted_users              0.000000
cast_total_facebook_likes    0.000000
actor_3_name                 0.132135
facenumber_in_poster         0.158562
plot_keywords                0.396406
movie_imdb_link              0.000000
num_user_for_reviews         0.000000
language                     0.052854
country                      0.000000
content_rating               0.000000
budget                       0.000000
title_year                   0.000000
actor_2_facebook_likes       0.026427
imdb_score                   0.000000
aspect_ratio                 0.000000
movie_facebook_likes         0.000000
dtype: float64

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [16]:
# Write your code for unit conversion hereM
movies1["budget_dollor"] = movies1["budget"]
movies1["budget_dollor"] = movies1["budget_dollor"] / 1000000 
movies1["budget_dollor"] = movies1["budget_dollor"].map("${:,.2f}M".format)
movies1["gross_dollor"] = movies1["gross"]
movies1["gross_dollor"] = movies1["gross_dollor"] / 1000000 
movies1["gross_dollor"] = movies1["gross_dollor"].map("${:,.2f}M".format)
movies1

C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2380794679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["budget_dollor"] = movies1["budget"]
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2380794679.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["budget_dollor"] = movies1["budget_dollor"] / 1000000
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2380794679.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["budget_dollor"] = movies1["budget_dollor"].map("${:,.2f}M".format)
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2380794679.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["gross_dollor"] = movies1["gross"]
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2380794679.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["gross_dollor"] = movies1["gross_dollor"] / 1000000
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2380794679.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["gross_dollor"] = movies1["gross_dollor"].map("${:,.2f}M".format)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,$237.00M,$760.51M
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,$300.00M,$309.40M
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,$245.00M,$200.07M
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,$250.00M,$448.13M
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000,$263.70M,$73.06M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,France,R,4500.0,2004.0,133.0,6.9,2.35,171,$0.00M,$0.14M
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697,$0.01M,$0.67M
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000,$0.01M,$0.42M
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,USA,R,7000.0,1992.0,20.0,6.9,1.37,0,$0.01M,$2.04M
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,$0.00M,$0.09M

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [17]:
# Write your code for creating the profit column herp
movies1["profit"] = movies1["gross"] - movies1["budget"]
movies1["profit_dollor"] = movies1["profit"] / 1000000 
movies1["profit_dollor"] = movies1["profit_dollor"].map("${:,.2f}M".format)
movies1

C:\Users\hP\AppData\Local\Temp\ipykernel_9188\4088534816.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["profit"] = movies1["gross"] - movies1["budget"]
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\4088534816.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["profit_dollor"] = movies1["profit"] / 1000000
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\4088534816.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1["profit_dollor"] = movies1["profit_dollor"].map("${:,.2f}M".format)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,237000000.0,2009.0,936.0,7.9,1.78,33000,$237.00M,$760.51M,523505847.0,$523.51M
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,300000000.0,2007.0,5000.0,7.1,2.35,0,$300.00M,$309.40M,9404152.0,$9.40M
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,245000000.0,2015.0,393.0,6.8,2.35,85000,$245.00M,$200.07M,-44925825.0,$-44.93M
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,250000000.0,2012.0,23000.0,8.5,2.35,164000,$250.00M,$448.13M,198130642.0,$198.13M
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,263700000.0,2012.0,632.0,6.6,2.35,24000,$263.70M,$73.06M,-190641321.0,$-190.64M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,4500.0,2004.0,133.0,6.9,2.35,171,$0.00M,$0.14M,131507.0,$0.13M
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,10000.0,2000.0,0.0,7.5,1.85,697,$0.01M,$0.67M,663780.0,$0.66M
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,7000.0,2004.0,45.0,7.0,1.85,19000,$0.01M,$0.42M,417760.0,$0.42M
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,7000.0,1992.0,20.0,6.9,1.37,0,$0.01M,$2.04M,2033920.0,$2.03M
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,1100.0,2004.0,23.0,6.6,1.85,456,$0.00M,$0.09M,84122.0,$0.08M

In [18]:
# Write your code for sorting the dataframe here
movies2=movies1.sort_values(by=['profit'], ascending=False)
movies2

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,2.370000e+08,2009.0,936.0,7.9,1.78,33000,$237.00M,$760.51M,5.235058e+08,$523.51M
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1.500000e+08,2015.0,2000.0,7.0,2.00,150000,$150.00M,$652.18M,5.021773e+08,$502.18M
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2.000000e+08,1997.0,14000.0,7.7,2.35,26000,$200.00M,$658.67M,4.586723e+08,$458.67M
3024,Color,George Lucas,282.0,125.0,0.0,504.0,Peter Cushing,11000.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,...,1.100000e+07,1977.0,1000.0,8.7,2.35,33000,$11.00M,$460.94M,4.499357e+08,$449.94M
3080,Color,Steven Spielberg,215.0,120.0,14000.0,548.0,Dee Wallace,861.0,434949459.0,Family|Sci-Fi,...,1.050000e+07,1982.0,725.0,7.9,1.85,34000,$10.50M,$434.95M,4.244495e+08,$424.45M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Color,Katsuhiro Ôtomo,105.0,103.0,78.0,101.0,Robin Atkin Downes,488.0,410388.0,Action|Adventure|Animation|Family|Sci-Fi|Thriller,...,2.127520e+09,2004.0,336.0,6.9,1.85,973,"$2,127.52M",$0.41M,-2.127110e+09,"$-2,127.11M"
2323,Color,Hayao Miyazaki,174.0,134.0,6000.0,745.0,Jada Pinkett Smith,893.0,2298191.0,Adventure|Animation|Fantasy,...,2.400000e+09,1997.0,851.0,8.4,1.85,11000,"$2,400.00M",$2.30M,-2.397702e+09,"$-2,397.70M"
3005,Color,Lajos Koltai,73.0,134.0,45.0,0.0,Péter Fancsikai,9.0,195888.0,Drama|Romance|War,...,2.500000e+09,2005.0,2.0,7.1,2.35,607,"$2,500.00M",$0.20M,-2.499804e+09,"$-2,499.80M"
3859,Color,Chan-wook Park,202.0,112.0,0.0,38.0,Yeong-ae Lee,717.0,211667.0,Crime|Drama,...,4.200000e+09,2005.0,126.0,7.7,2.35,4000,"$4,200.00M",$0.21M,-4.199788e+09,"$-4,199.79M"
2988,Color,Joon-ho Bong,363.0,110.0,584.0,74.0,Kang-ho Song,629.0,2201412.0,Comedy|Drama|Horror|Sci-Fi,...,1.221550e+10,2006.0,398.0,7.0,1.85,7000,"$12,215.50M",$2.20M,-1.221330e+10,"$-12,213.30M"

In [19]:
movies2["profit_dollor"].head(10)

0       $523.51M
29      $502.18M
26      $458.67M
3024    $449.94M
3080    $424.45M
794     $403.28M
17      $403.28M
509     $377.78M
240     $359.54M
66      $348.32M
Name: profit_dollor, dtype: object

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [20]:
# Write your code for dropping duplicate values here
movies3 = movies1.drop_duplicates(subset=["profit"], keep=False)
movies3

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,237000000.0,2009.0,936.0,7.9,1.78,33000,$237.00M,$760.51M,523505847.0,$523.51M
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,300000000.0,2007.0,5000.0,7.1,2.35,0,$300.00M,$309.40M,9404152.0,$9.40M
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,245000000.0,2015.0,393.0,6.8,2.35,85000,$245.00M,$200.07M,-44925825.0,$-44.93M
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,250000000.0,2012.0,23000.0,8.5,2.35,164000,$250.00M,$448.13M,198130642.0,$198.13M
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,263700000.0,2012.0,632.0,6.6,2.35,24000,$263.70M,$73.06M,-190641321.0,$-190.64M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,4500.0,2004.0,133.0,6.9,2.35,171,$0.00M,$0.14M,131507.0,$0.13M
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,10000.0,2000.0,0.0,7.5,1.85,697,$0.01M,$0.67M,663780.0,$0.66M
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,7000.0,2004.0,45.0,7.0,1.85,19000,$0.01M,$0.42M,417760.0,$0.42M
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,7000.0,1992.0,20.0,6.9,1.37,0,$0.01M,$2.04M,2033920.0,$2.03M
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,1100.0,2004.0,23.0,6.6,1.85,456,$0.00M,$0.09M,84122.0,$0.08M

In [21]:
# Write code for repeating subtask 2 here
movies4=movies3.sort_values(by=['profit'], ascending=False)
movies4["profit_dollor"].head(10)

0       $523.51M
29      $502.18M
26      $458.67M
3024    $449.94M
3080    $424.45M
509     $377.78M
240     $359.54M
66      $348.32M
439     $330.00M
812     $305.02M
Name: profit_dollor, dtype: object

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

In [22]:
movies4["director_name"].head(10)

0           James Cameron
29        Colin Trevorrow
26          James Cameron
3024         George Lucas
3080     Steven Spielberg
509          Roger Allers
240          George Lucas
66      Christopher Nolan
439             Gary Ross
812            Tim Miller
Name: director_name, dtype: object

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [23]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
filter_movies=movies1[movies1["num_voted_users"] > 25000 ]
IMDb_Top_250=filter_movies.sort_values(by=['imdb_score'], ascending=False).head(250)
IMDb_Top_250['rank'] = range(1,251)
IMDb_Top_250

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,rank
1937,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,...,1994.0,745.0,9.3,1.85,108000,$25.00M,$28.34M,3341469.0,$3.34M,1
3466,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,...,1972.0,10000.0,9.2,1.85,43000,$6.00M,$134.82M,128821952.0,$128.82M,2
66,Color,Christopher Nolan,645.0,152.0,22000.0,11000.0,Heath Ledger,23000.0,533316061.0,Action|Crime|Drama|Thriller,...,2008.0,13000.0,9.0,2.35,37000,$185.00M,$533.32M,348316061.0,$348.32M,3
2837,Color,Francis Ford Coppola,149.0,220.0,0.0,3000.0,Al Pacino,22000.0,57300000.0,Crime|Drama,...,1974.0,14000.0,9.0,1.85,14000,$13.00M,$57.30M,44300000.0,$44.30M,4
4498,Color,Sergio Leone,181.0,142.0,0.0,24.0,Luigi Pistilli,16000.0,6100000.0,Western,...,1966.0,34.0,8.9,2.35,20000,$1.20M,$6.10M,4900000.0,$4.90M,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Color,Doug Liman,585.0,113.0,218.0,509.0,Lara Pulver,10000.0,100189501.0,Action|Adventure|Sci-Fi,...,2014.0,854.0,7.9,2.35,77000,$178.00M,$100.19M,-77810499.0,$-77.81M,246
3452,Color,Paul Haggis,287.0,115.0,549.0,911.0,Loretta Devine,3000.0,54557348.0,Crime|Drama|Thriller,...,2004.0,912.0,7.9,2.35,18000,$6.50M,$54.56M,48057348.0,$48.06M,247
3595,Color,Darren Aronofsky,391.0,109.0,0.0,120.0,John D'Leo,1000.0,26236603.0,Drama|Sport,...,2008.0,245.0,7.9,2.35,10000,$6.00M,$26.24M,20236603.0,$20.24M,248
89,Color,Don Hall,384.0,102.0,38.0,562.0,Daniel Henney,756.0,222487711.0,Action|Adventure|Animation|Comedy|Drama|Family...,...,2014.0,719.0,7.9,2.39,41000,$165.00M,$222.49M,57487711.0,$57.49M,249
3677,Color,Christophe Barratier,112.0,97.0,25.0,57.0,François Berléand,517.0,3629758.0,Drama|Music,...,2004.0,86.0,7.9,2.35,0,$5.50M,$3.63M,-1870242.0,$-1.87M,250

In [24]:
#IMDb_Top= IMDb_Top_250[IMDb_Top_250['language']!= 'English']
Top_Foreign_Lang_Film= IMDb_Top_250[IMDb_Top_250['language']=='English']
Top_Foreign_Lang_Film

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,rank
1937,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,...,1994.0,745.0,9.3,1.85,108000,$25.00M,$28.34M,3341469.0,$3.34M,1
3466,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,...,1972.0,10000.0,9.2,1.85,43000,$6.00M,$134.82M,128821952.0,$128.82M,2
66,Color,Christopher Nolan,645.0,152.0,22000.0,11000.0,Heath Ledger,23000.0,533316061.0,Action|Crime|Drama|Thriller,...,2008.0,13000.0,9.0,2.35,37000,$185.00M,$533.32M,348316061.0,$348.32M,3
2837,Color,Francis Ford Coppola,149.0,220.0,0.0,3000.0,Al Pacino,22000.0,57300000.0,Crime|Drama,...,1974.0,14000.0,9.0,1.85,14000,$13.00M,$57.30M,44300000.0,$44.30M,4
1874,Black and White,Steven Spielberg,174.0,185.0,14000.0,212.0,Embeth Davidtz,14000.0,96067179.0,Biography|Drama|History,...,1993.0,795.0,8.9,1.85,41000,$22.00M,$96.07M,74067179.0,$74.07M,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3361,Color,Jonathan Dayton,270.0,101.0,36.0,27.0,Steven Christopher Parker,7000.0,59889948.0,Comedy|Drama,...,2006.0,150.0,7.9,2.35,15000,$8.00M,$59.89M,51889948.0,$51.89M,245
75,Color,Doug Liman,585.0,113.0,218.0,509.0,Lara Pulver,10000.0,100189501.0,Action|Adventure|Sci-Fi,...,2014.0,854.0,7.9,2.35,77000,$178.00M,$100.19M,-77810499.0,$-77.81M,246
3452,Color,Paul Haggis,287.0,115.0,549.0,911.0,Loretta Devine,3000.0,54557348.0,Crime|Drama|Thriller,...,2004.0,912.0,7.9,2.35,18000,$6.50M,$54.56M,48057348.0,$48.06M,247
3595,Color,Darren Aronofsky,391.0,109.0,0.0,120.0,John D'Leo,1000.0,26236603.0,Drama|Sport,...,2008.0,245.0,7.9,2.35,10000,$6.00M,$26.24M,20236603.0,$20.24M,248
89,Color,Don Hall,384.0,102.0,38.0,562.0,Daniel Henney,756.0,222487711.0,Action|Adventure|Animation|Comedy|Drama|Family...,...,2014.0,719.0,7.9,2.39,41000,$165.00M,$222.49M,57487711.0,$57.49M,249

In [25]:
Top_Foreign_Lang_Film = IMDb_Top= IMDb_Top_250[IMDb_Top_250['language']!= 'English'] # Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,rank
4498,Color,Sergio Leone,181.0,142.0,0.0,24.0,Luigi Pistilli,16000.0,6100000.0,Western,...,1966.0,34.0,8.9,2.35,20000,$1.20M,$6.10M,4.900000e+06,$4.90M,5
4747,Black and White,Akira Kurosawa,153.0,202.0,0.0,4.0,Minoru Chiaki,304.0,269061.0,Action|Adventure|Drama,...,1954.0,8.0,8.7,1.37,11000,$2.00M,$0.27M,-1.730939e+06,$-1.73M,18
4029,Color,Fernando Meirelles,214.0,135.0,353.0,40.0,Seu Jorge,1000.0,7563397.0,Crime|Drama,...,2002.0,69.0,8.7,1.85,28000,$3.30M,$7.56M,4.263397e+06,$4.26M,19
2373,Color,Hayao Miyazaki,246.0,125.0,6000.0,7.0,Ryûnosuke Kamiki,17.0,10049886.0,Adventure|Animation|Family|Fantasy,...,2001.0,10.0,8.6,1.85,28000,$19.00M,$10.05M,-8.950114e+06,$-8.95M,26
4259,Color,Florian Henckel von Donnersmarck,215.0,137.0,207.0,155.0,Ulrich Mühe,380.0,11284657.0,Drama|Thriller,...,2006.0,284.0,8.5,2.35,39000,$2.00M,$11.28M,9.284657e+06,$9.28M,31
4921,Color,Majid Majidi,46.0,89.0,373.0,27.0,Amir Farrokh Hashemian,36.0,925402.0,Drama|Family,...,1997.0,35.0,8.5,1.85,0,$0.18M,$0.93M,7.454020e+05,$0.75M,45
4105,Color,Chan-wook Park,305.0,120.0,0.0,38.0,Ji-tae Yu,717.0,2181290.0,Drama|Mystery|Thriller,...,2003.0,78.0,8.4,2.35,43000,$3.00M,$2.18M,-8.187100e+05,$-0.82M,50
2323,Color,Hayao Miyazaki,174.0,134.0,6000.0,745.0,Jada Pinkett Smith,893.0,2298191.0,Adventure|Animation|Fantasy,...,1997.0,851.0,8.4,1.85,11000,"$2,400.00M",$2.30M,-2.397702e+09,"$-2,397.70M",51
1298,Black and White,Jean-Pierre Jeunet,242.0,122.0,0.0,54.0,Jamel Debbouze,326.0,33201661.0,Comedy|Romance,...,2001.0,326.0,8.4,2.35,39000,$77.00M,$33.20M,-4.379834e+07,$-43.80M,54
2970,Color,Wolfgang Petersen,96.0,293.0,249.0,18.0,Martin Semmelrogge,362.0,11433134.0,Adventure|Drama|Thriller|War,...,1981.0,21.0,8.4,1.85,11000,$14.00M,$11.43M,-2.566866e+06,$-2.57M,55
4659,Color,Asghar Farhadi,354.0,123.0,0.0,620.0,Leila Hatami,786.0,7098492.0,Drama|Mystery,...,2011.0,712.0,8.4,1.85,48000,$0.50M,$7.10M,6.598492e+06,$6.60M,60
2829,Color,Oliver Hirschbiegel,192.0,178.0,101.0,471.0,Bruno Ganz,918.0,5501940.0,Biography|Drama|History|War,...,2004.0,653.0,8.3,1.85,14000,$13.50M,$5.50M,-7.998060e+06,$-8.00M,79
2734,Black and White,Fritz Lang,260.0,145.0,756.0,18.0,Gustav Fröhlich,136.0,26435.0,Drama|Sci-Fi,...,1927.0,23.0,8.3,1.33,12000,$6.00M,$0.03M,-5.973565e+06,$-5.97M,80
4033,Color,Thomas Vinterberg,349.0,115.0,346.0,26.0,Alexandra Rapaport,74.0,610968.0,Drama,...,2012.0,69.0,8.3,2.35,60000,$3.80M,$0.61M,-3.189032e+06,$-3.19M,83
3550,Color,Denis Villeneuve,226.0,139.0,777.0,58.0,Mélissa Désormeaux-Poulin,131.0,6857096.0,Drama|Mystery|War,...,2010.0,66.0,8.2,1.85,37000,$6.80M,$6.86M,5.709600e+04,$0.06M,89
2551,Color,Guillermo del Toro,406.0,112.0,0.0,250.0,Maribel Verdú,634.0,37623143.0,Drama|Fantasy|War,...,2006.0,269.0,8.2,1.85,27000,$13.50M,$37.62M,2.412314e+07,$24.12M,90
2047,Color,Hayao Miyazaki,212.0,119.0,6000.0,422.0,Blythe Danner,23000.0,4710455.0,Adventure|Animation|Family|Fantasy,...,2004.0,713.0,8.2,1.85,13000,$24.00M,$4.71M,-1.928954e+07,$-19.29M,93
4000,Color,Juan José Campanella,262.0,129.0,195.0,50.0,Soledad Villamil,827.0,20167424.0,Drama|Mystery|Thriller,...,2009.0,88.0,8.2,2.35,33000,$2.00M,$20.17M,1.816742e+07,$18.17M,104
3423,Color,Katsuhiro Ôtomo,150.0,124.0,78.0,4.0,Takeshi Kusao,6.0,439162.0,Action|Animation|Sci-Fi,...,1988.0,5.0,8.1,1.85,0,"$1,100.00M",$0.44M,-1.099561e+09,"$-1,099.56M",112
2914,Color,Je-kyu Kang,86.0,148.0,16.0,489.0,Bin Won,717.0,1110186.0,Action|Drama|War,...,2004.0,517.0,8.1,2.35,0,$12.80M,$1.11M,-1.168981e+07,$-11.69M,117
4461,Color,Thomas Vinterberg,98.0,105.0,346.0,141.0,Paprika Steen,280.0,1647780.0,Drama,...,1998.0,278.0,8.1,1.33,5000,$1.30M,$1.65M,3.477800e+05,$0.35M,123
3553,Color,José Padilha,142.0,115.0,294.0,15.0,Fernanda Machado,585.0,8060.0,Action|Crime|Drama|Thriller,...,2007.0,39.0,8.1,1.85,11000,$4.00M,$0.01M,-3.991940e+06,$-3.99M,149
4267,Color,Alejandro G. Iñárritu,157.0,115.0,0.0,35.0,Jorge Salinas,85.0,5383834.0,Drama|Thriller,...,2000.0,79.0,8.1,1.85,11000,$2.00M,$5.38M,3.383834e+06,$3.38M,150
2830,Color,Alejandro Amenábar,157.0,125.0,448.0,93.0,Lola Dueñas,273.0,2086345.0,Biography|Drama|Romance,...,2004.0,114.0,8.1,2.35,0,$10.00M,$2.09M,-7.913655e+06,$-7.91M,152
4897,Color,Sergio Leone,122.0,99.0,0.0,93.0,Gian Maria Volontè,16000.0,3500000.0,Action|Drama|Western,...,1964.0,360.0,8.0,2.35,0,$0.20M,$3.50M,3.300000e+06,$3.30M,166
4284,Color,Ari Folman,231.0,90.0,56.0,0.0,Ronny Dayag,56.0,2283276.0,Animation|Biography|Documentary|Drama|History|War,...,2008.0,0.0,8.0,1.85,0,$1.50M,$2.28M,7.832760e+05,$0.78M,189
3456,Color,Vincent Paronnaud,242.0,89.0,10.0,106.0,Gena Rowlands,963.0,4443403.0,Animation|Biography|Drama|War,...,2007.0,545.0,8.0,1.85,14000,$7.30M,$4.44M,-2.856597e+06,$-2.86M,190
4144,Color,Walter Salles,71.0,113.0,179.0,11.0,Matheus Nachtergaele,119.0,5595428.0,Drama,...,1998.0,14.0,8.0,2.35,0,$2.90M,$5.60M,2.695428e+06,$2.70M,191
3344,Color,Karan Johar,210.0,128.0,160.0,81.0,Jimmy Shergill,8000.0,4018695.0,Adventure|Drama|Thriller,...,2010.0,327.0,8.0,2.35,27000,$12.00M,$4.02M,-7.981305e+06,$-7.98M,197
2493,Black and White,Yimou Zhang,283.0,80.0,611.0,576.0,Tony Chiu Wai Leung,5000.0,84961.0,Action|Adventure|History,...,2002.0,643.0,7.9,2.35,0,$31.00M,$0.08M,-3.091504e+07,$-30.92M,225
1171,Black and White,Yimou Zhang,283.0,80.0,611.0,576.0,Tony Chiu Wai Leung,5000.0,84961.0,Action|Adventure|History,...,2002.0,643.0,7.9,2.35,0,$31.00M,$0.08M,-3.091504e+07,$-30.92M,226
2605,Color,Ang Lee,287.0,120.0,0.0,5.0,Pei-Pei Cheng,103.0,128067808.0,Action|Drama|Romance,...,2000.0,21.0,7.9,2.35,0,$15.00M,$128.07M,1.130678e+08,$113.07M,234
2863,Color,Clint Eastwood,251.0,141.0,16000.0,78.0,Kazunari Ninomiya,378.0,13753931.0,Drama|History|War,...,2006.0,85.0,7.9,2.35,5000,$19.00M,$13.75M,-5.246069e+06,$-5.25M,236
3264,Color,Michael Haneke,447.0,127.0,0.0,319.0,Emmanuelle Riva,678.0,225377.0,Drama|Romance,...,2012.0,432.0,7.9,1.85,33000,$8.90M,$0.23M,-8.674623e+06,$-8.67M,241
3677,Color,Christophe Barratier,112.0,97.0,25.0,57.0,François Berléand,517.0,3629758.0,Drama|Music,...,2004.0,86.0,7.9,2.35,0,$5.50M,$3.63M,-1.870242e+06,$-1.87M,250

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

In [26]:
veer = IMDb_Top_250[IMDb_Top_250['movie_title']=='Veer-Zaara']
veer

Empty DataFrame
Columns: [color, director_name, num_critic_for_reviews, duration, director_facebook_likes, actor_3_facebook_likes, actor_2_name, actor_1_facebook_likes, gross, genres, actor_1_name, movie_title, num_voted_users, cast_total_facebook_likes, actor_3_name, facenumber_in_poster, plot_keywords, movie_imdb_link, num_user_for_reviews, language, country, content_rating, budget, title_year, actor_2_facebook_likes, imdb_score, aspect_ratio, movie_facebook_likes, budget_dollor, gross_dollor, profit, profit_dollor, rank]
Index: []

[0 rows x 33 columns]

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [27]:
# Write your code for extracting the top 10 directors here
top10director = filter_movies.sort_values(by=['imdb_score'], ascending=False).head(10)
top10director['director_name']

1937          Frank Darabont
3466    Francis Ford Coppola
66         Christopher Nolan
2837    Francis Ford Coppola
4498            Sergio Leone
1874        Steven Spielberg
339            Peter Jackson
3355       Quentin Tarantino
836          Robert Zemeckis
270            Peter Jackson
Name: director_name, dtype: object

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [28]:
# Write your code for extracting the first two genres of each movie here
genres_spilt = movies1['genres'].str.split('|',expand=True)
movies1['genres_1'] = genres_spilt[0]
movies1['genres_2'] = genres_spilt[1]
movies1['genres_2'].fillna(movies1['genres_1'],inplace=True)
movies1

C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2505610335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1['genres_1'] = genres_spilt[0]
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2505610335.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1['genres_2'] = genres_spilt[1]
C:\Users\hP\AppData\Local\Temp\ipykernel_9188\2505610335.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1['genres_2'].fillna(movies1['genres_1'],inplace=True)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,genres_1,genres_2
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,936.0,7.9,1.78,33000,$237.00M,$760.51M,523505847.0,$523.51M,Action,Adventure
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,5000.0,7.1,2.35,0,$300.00M,$309.40M,9404152.0,$9.40M,Action,Adventure
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,393.0,6.8,2.35,85000,$245.00M,$200.07M,-44925825.0,$-44.93M,Action,Adventure
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,23000.0,8.5,2.35,164000,$250.00M,$448.13M,198130642.0,$198.13M,Action,Thriller
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,632.0,6.6,2.35,24000,$263.70M,$73.06M,-190641321.0,$-190.64M,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,133.0,6.9,2.35,171,$0.00M,$0.14M,131507.0,$0.13M,Drama,Music
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,0.0,7.5,1.85,697,$0.01M,$0.67M,663780.0,$0.66M,Drama,Drama
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,45.0,7.0,1.85,19000,$0.01M,$0.42M,417760.0,$0.42M,Drama,Sci-Fi
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,20.0,6.9,1.37,0,$0.01M,$2.04M,2033920.0,$2.03M,Action,Crime
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,23.0,6.6,1.85,456,$0.00M,$0.09M,84122.0,$0.08M,Documentary,Documentary

In [29]:
movies_by_segment = movies1.groupby(['genres_1','genres_2']).size().reset_index(name='count')# Write your code for grouping the dataframe here
movies_by_segment

    genres_1   genres_2  count
0     Action     Action      6
1     Action  Adventure    414
2     Action  Animation      8
3     Action  Biography     13
4     Action     Comedy    130
..       ...        ...    ...
94   Mystery   Thriller     17
95   Romance     Sci-Fi      1
96    Sci-Fi   Thriller      7
97  Thriller   Thriller      1
98   Western    Western      3

[99 rows x 3 columns]

In [30]:
PopGenre = filter_movies.sort_values(by=['gross'], ascending=False).head(5)
PopGenre
# Write your code for getting the 5 most popular combo of genres here

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,237000000.0,2009.0,936.0,7.9,1.78,33000,$237.00M,$760.51M,523505847.0,$523.51M
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,200000000.0,1997.0,14000.0,7.7,2.35,26000,$200.00M,$658.67M,458672302.0,$458.67M
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,150000000.0,2015.0,2000.0,7.0,2.00,150000,$150.00M,$652.18M,502177271.0,$502.18M
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,220000000.0,2012.0,21000.0,8.1,1.85,123000,$220.00M,$623.28M,403279547.0,$403.28M
794,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,220000000.0,2012.0,21000.0,8.1,1.85,123000,$220.00M,$623.28M,403279547.0,$403.28M

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [73]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies1[movies1['actor_1_name']=='Meryl Streep']
Meryl_Streep
# Include all movies in which Meryl_Streep is the lead

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,genres_1,genres_2
410,Color,Nancy Meyers,187.0,120.0,278.0,963.0,Hunter Parrish,11000.0,112703470.0,Comedy|Drama|Romance,...,2000.0,6.6,1.85,0,$85.00M,$112.70M,27703470.0,$27.70M,Comedy,Drama
1106,Color,Curtis Hanson,42.0,111.0,161.0,132.0,Glenn Morshower,11000.0,46815748.0,Action|Adventure|Crime|Thriller,...,894.0,6.3,2.35,0,$45.00M,$46.82M,1815748.0,$1.82M,Action,Adventure
1204,Color,Nora Ephron,252.0,123.0,0.0,923.0,Mary Lynn Rajskub,11000.0,94125426.0,Biography|Drama|Romance,...,935.0,7.0,1.85,13000,$40.00M,$94.13M,54125426.0,$54.13M,Biography,Drama
1408,Color,David Frankel,208.0,109.0,64.0,505.0,Anne Hathaway,11000.0,124732962.0,Comedy|Drama|Romance,...,11000.0,6.8,2.35,0,$35.00M,$124.73M,89732962.0,$89.73M,Comedy,Drama
1483,Color,Robert Redford,227.0,92.0,0.0,10000.0,Tom Cruise,11000.0,14998070.0,Drama|Thriller|War,...,10000.0,6.2,2.35,0,$35.00M,$15.00M,-20001930.0,$-20.00M,Drama,Thriller
1575,Color,Sydney Pollack,66.0,161.0,521.0,184.0,Michael Gough,11000.0,87100000.0,Biography|Drama|Romance,...,920.0,7.2,1.85,0,$31.00M,$87.10M,56100000.0,$56.10M,Biography,Drama
1618,Color,David Frankel,234.0,100.0,64.0,329.0,Steve Carell,11000.0,63536011.0,Comedy|Drama|Romance,...,7000.0,6.3,2.35,0,$30.00M,$63.54M,33536011.0,$33.54M,Comedy,Drama
1674,Color,Carl Franklin,64.0,127.0,73.0,433.0,William Hurt,11000.0,23209440.0,Drama,...,882.0,7.0,1.85,592,$30.00M,$23.21M,-6790560.0,$-6.79M,Drama,Drama
1925,Color,Stephen Daldry,174.0,114.0,335.0,530.0,Stephen Dillane,11000.0,41597830.0,Drama|Romance,...,577.0,7.6,1.85,0,$25.00M,$41.60M,16597830.0,$16.60M,Drama,Romance
2781,Color,Phyllida Lloyd,331.0,105.0,58.0,583.0,Jim Broadbent,11000.0,29959436.0,Biography|Drama|History,...,1000.0,6.4,2.35,18000,$13.00M,$29.96M,16959436.0,$16.96M,Biography,Drama
3135,Color,Robert Altman,211.0,105.0,500.0,718.0,Virginia Madsen,11000.0,20338609.0,Comedy|Drama|Music,...,912.0,6.8,2.35,683,$10.00M,$20.34M,10338609.0,$10.34M,Comedy,Drama

In [74]:
Leo_Caprio = movies1[movies1['actor_1_name']=='Leonardo DiCaprio']
Leo_Caprio
# Include all movies in which Leo_Caprio is the lead

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,genres_1,genres_2
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,14000.0,7.7,2.35,26000,$200.00M,$658.67M,458672302.0,$458.67M,Drama,Romance
50,Color,Baz Luhrmann,490.0,143.0,1000.0,77.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,509.0,7.3,2.35,115000,$105.00M,$144.81M,39812796.0,$39.81M,Drama,Romance
97,Color,Christopher Nolan,642.0,148.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,...,27000.0,8.8,2.35,175000,$160.00M,$292.57M,132568851.0,$132.57M,Action,Adventure
179,Color,Alejandro G. Iñárritu,556.0,156.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,...,27000.0,8.1,2.35,190000,$135.00M,$183.64M,48635922.0,$48.64M,Adventure,Drama
257,Black and White,Martin Scorsese,267.0,170.0,17000.0,827.0,Adam Scott,29000.0,102608827.0,Biography|Drama,...,3000.0,7.5,2.35,0,$110.00M,$102.61M,-7391173.0,$-7.39M,Biography,Drama
296,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,11000.0,8.5,2.35,199000,$100.00M,$162.80M,62804648.0,$62.80M,Drama,Western
307,Color,Edward Zwick,166.0,143.0,380.0,452.0,Djimon Hounsou,29000.0,57366262.0,Adventure|Drama|Thriller,...,3000.0,8.0,2.35,14000,$100.00M,$57.37M,-42633738.0,$-42.63M,Adventure,Drama
308,Color,Martin Scorsese,606.0,240.0,17000.0,4000.0,Matthew McConaughey,29000.0,116866727.0,Biography|Comedy|Crime|Drama,...,11000.0,8.2,2.35,138000,$100.00M,$116.87M,16866727.0,$16.87M,Biography,Comedy
326,Color,Martin Scorsese,233.0,216.0,17000.0,1000.0,Liam Neeson,29000.0,77679638.0,Crime|Drama,...,14000.0,7.5,2.35,0,$100.00M,$77.68M,-22320362.0,$-22.32M,Crime,Drama
361,Color,Martin Scorsese,352.0,151.0,17000.0,1000.0,Matt Damon,29000.0,132373442.0,Crime|Drama|Thriller,...,13000.0,8.5,2.35,29000,$90.00M,$132.37M,42373442.0,$42.37M,Crime,Drama
452,Color,Martin Scorsese,490.0,138.0,17000.0,163.0,Joseph Sikora,29000.0,127968405.0,Mystery|Thriller,...,223.0,8.1,2.35,53000,$80.00M,$127.97M,47968405.0,$47.97M,Mystery,Thriller
641,Color,Ridley Scott,238.0,128.0,0.0,135.0,Simon McBurney,29000.0,39380442.0,Action|Drama|Thriller,...,149.0,7.1,2.35,0,$70.00M,$39.38M,-30619558.0,$-30.62M,Action,Drama
911,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,15000.0,8.0,1.85,15000,$52.00M,$164.44M,112435221.0,$112.44M,Biography,Crime
990,Color,Danny Boyle,118.0,119.0,0.0,39.0,Virginie Ledoyen,29000.0,39778599.0,Adventure|Drama|Thriller,...,414.0,6.6,2.35,0,$50.00M,$39.78M,-10221401.0,$-10.22M,Adventure,Drama
1114,Color,Sam Mendes,323.0,119.0,0.0,10000.0,Kate Winslet,29000.0,22877808.0,Drama|Romance,...,14000.0,7.3,2.35,0,$35.00M,$22.88M,-12122192.0,$-12.12M,Drama,Romance
1422,Color,Randall Wallace,83.0,132.0,130.0,80.0,Anne Parillaud,29000.0,56876365.0,Action|Adventure,...,130.0,6.4,1.85,0,$35.00M,$56.88M,21876365.0,$21.88M,Action,Adventure
1453,Color,Clint Eastwood,392.0,137.0,16000.0,363.0,Naomi Watts,29000.0,37304950.0,Biography|Crime|Drama,...,6000.0,6.6,2.35,16000,$35.00M,$37.30M,2304950.0,$2.30M,Biography,Crime
1560,Black and White,Sam Raimi,63.0,107.0,0.0,159.0,Pat Hingle,29000.0,18636537.0,Action|Thriller|Western,...,165.0,6.4,1.85,0,$32.00M,$18.64M,-13363463.0,$-13.36M,Action,Thriller
2067,Color,Jerry Zaks,45.0,98.0,4.0,11000.0,Robert De Niro,29000.0,12782508.0,Drama,...,22000.0,6.7,1.85,1000,$23.00M,$12.78M,-10217492.0,$-10.22M,Drama,Drama
2757,Color,Baz Luhrmann,106.0,120.0,1000.0,954.0,Harold Perrineau,29000.0,46338728.0,Drama|Romance,...,1000.0,6.8,2.35,10000,$14.50M,$46.34M,31838728.0,$31.84M,Drama,Romance
3476,Color,Baz Luhrmann,490.0,143.0,1000.0,76.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,509.0,7.3,2.35,115000,$105.00M,$144.81M,39812796.0,$39.81M,Drama,Romance

In [75]:
Brad_Pitt = movies1[movies1['actor_1_name']=='Brad Pitt']
Brad_Pitt
# Include all movies in which Brad_Pitt is the lead

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,genres_1,genres_2
101,Color,David Fincher,362.0,166.0,21000.0,919.0,Jason Flemyng,11000.0,127490802.0,Drama|Fantasy|Romance,...,1000.0,7.8,2.35,23000,$150.00M,$127.49M,-22509198.0,$-22.51M,Drama,Fantasy
147,Color,Wolfgang Petersen,220.0,196.0,249.0,844.0,Orlando Bloom,11000.0,133228348.0,Adventure,...,5000.0,7.2,2.35,0,$175.00M,$133.23M,-41771652.0,$-41.77M,Adventure,Adventure
254,Color,Steven Soderbergh,198.0,125.0,0.0,350.0,Julia Roberts,11000.0,125531634.0,Crime|Thriller,...,8000.0,6.4,2.35,0,$110.00M,$125.53M,15531634.0,$15.53M,Crime,Thriller
255,Color,Doug Liman,233.0,126.0,218.0,322.0,Angelina Jolie Pitt,11000.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,...,11000.0,6.5,2.35,0,$120.00M,$186.34M,66336103.0,$66.34M,Action,Comedy
382,Color,Tony Scott,142.0,114.0,12000.0,307.0,Stephen Dillane,11000.0,26871.0,Action|Crime|Thriller,...,577.0,7.0,2.35,0,$92.00M,$0.03M,-91973129.0,$-91.97M,Action,Crime
400,Color,Steven Soderbergh,186.0,116.0,0.0,471.0,Bernie Mac,11000.0,183405771.0,Crime|Thriller,...,1000.0,7.8,2.35,0,$85.00M,$183.41M,98405771.0,$98.41M,Crime,Thriller
470,Color,David Ayer,406.0,134.0,452.0,697.0,Logan Lerman,11000.0,85707116.0,Action|Drama|War,...,8000.0,7.6,2.35,82000,$68.00M,$85.71M,17707116.0,$17.71M,Action,Drama
611,Color,Jean-Jacques Annaud,76.0,136.0,218.0,400.0,Mako,11000.0,37901509.0,Adventure|Biography|Drama|History|War,...,691.0,7.0,2.35,0,$70.00M,$37.90M,-32098491.0,$-32.10M,Adventure,Biography
683,Color,David Fincher,315.0,151.0,21000.0,637.0,Meat Loaf,11000.0,37023395.0,Drama,...,783.0,8.8,2.35,48000,$63.00M,$37.02M,-25976605.0,$-25.98M,Drama,Drama
792,Color,Patrick Gilmore,98.0,85.0,0.0,82.0,Adriano Giannini,11000.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,...,102.0,6.7,1.66,880,$60.00M,$26.29M,-33711680.0,$-33.71M,Adventure,Animation
940,Color,Neil Jordan,120.0,123.0,277.0,4000.0,Tom Cruise,11000.0,105264608.0,Drama|Fantasy|Horror,...,10000.0,7.6,1.85,11000,$60.00M,$105.26M,45264608.0,$45.26M,Drama,Fantasy
1490,Color,Terrence Malick,584.0,139.0,0.0,687.0,Tye Sheridan,11000.0,13303319.0,Drama|Fantasy,...,1000.0,6.7,1.85,39000,$32.00M,$13.30M,-18696681.0,$-18.70M,Drama,Fantasy
1722,Color,Andrew Dominik,273.0,160.0,181.0,820.0,Jeremy Renner,11000.0,3904982.0,Biography|Crime|Drama|History|Western,...,10000.0,7.5,2.35,0,$30.00M,$3.90M,-26095018.0,$-26.10M,Biography,Crime
2204,Color,Alejandro G. Iñárritu,285.0,143.0,0.0,51.0,Harriet Walter,11000.0,34300771.0,Drama,...,119.0,7.5,1.85,0,$25.00M,$34.30M,9300771.0,$9.30M,Drama,Drama
2333,Color,Angelina Jolie Pitt,131.0,122.0,11000.0,188.0,Angelina Jolie Pitt,11000.0,531009.0,Drama|Romance,...,11000.0,5.3,2.35,0,$10.00M,$0.53M,-9468991.0,$-9.47M,Drama,Romance
2682,Color,Andrew Dominik,414.0,97.0,181.0,748.0,Sam Shepard,11000.0,14938570.0,Crime|Thriller,...,820.0,6.2,2.35,20000,$15.00M,$14.94M,-61430.0,$-0.06M,Crime,Thriller
2898,Color,Tony Scott,122.0,121.0,12000.0,975.0,Gary Oldman,11000.0,12281500.0,Action|Crime|Drama|Romance|Thriller,...,10000.0,8.0,2.35,15000,$13.00M,$12.28M,-718500.0,$-0.72M,Action,Crime

In [76]:
# Write your code for combining the three dataframes here
combined = pd.concat([Meryl_Streep, Leo_Caprio, Brad_Pitt],ignore_index=True)
combined

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,budget_dollor,gross_dollor,profit,profit_dollor,genres_1,genres_2
0,Color,Nancy Meyers,187.0,120.0,278.0,963.0,Hunter Parrish,11000.0,112703470.0,Comedy|Drama|Romance,...,2000.0,6.6,1.85,0,$85.00M,$112.70M,27703470.0,$27.70M,Comedy,Drama
1,Color,Curtis Hanson,42.0,111.0,161.0,132.0,Glenn Morshower,11000.0,46815748.0,Action|Adventure|Crime|Thriller,...,894.0,6.3,2.35,0,$45.00M,$46.82M,1815748.0,$1.82M,Action,Adventure
2,Color,Nora Ephron,252.0,123.0,0.0,923.0,Mary Lynn Rajskub,11000.0,94125426.0,Biography|Drama|Romance,...,935.0,7.0,1.85,13000,$40.00M,$94.13M,54125426.0,$54.13M,Biography,Drama
3,Color,David Frankel,208.0,109.0,64.0,505.0,Anne Hathaway,11000.0,124732962.0,Comedy|Drama|Romance,...,11000.0,6.8,2.35,0,$35.00M,$124.73M,89732962.0,$89.73M,Comedy,Drama
4,Color,Robert Redford,227.0,92.0,0.0,10000.0,Tom Cruise,11000.0,14998070.0,Drama|Thriller|War,...,10000.0,6.2,2.35,0,$35.00M,$15.00M,-20001930.0,$-20.00M,Drama,Thriller
5,Color,Sydney Pollack,66.0,161.0,521.0,184.0,Michael Gough,11000.0,87100000.0,Biography|Drama|Romance,...,920.0,7.2,1.85,0,$31.00M,$87.10M,56100000.0,$56.10M,Biography,Drama
6,Color,David Frankel,234.0,100.0,64.0,329.0,Steve Carell,11000.0,63536011.0,Comedy|Drama|Romance,...,7000.0,6.3,2.35,0,$30.00M,$63.54M,33536011.0,$33.54M,Comedy,Drama
7,Color,Carl Franklin,64.0,127.0,73.0,433.0,William Hurt,11000.0,23209440.0,Drama,...,882.0,7.0,1.85,592,$30.00M,$23.21M,-6790560.0,$-6.79M,Drama,Drama
8,Color,Stephen Daldry,174.0,114.0,335.0,530.0,Stephen Dillane,11000.0,41597830.0,Drama|Romance,...,577.0,7.6,1.85,0,$25.00M,$41.60M,16597830.0,$16.60M,Drama,Romance
9,Color,Phyllida Lloyd,331.0,105.0,58.0,583.0,Jim Broadbent,11000.0,29959436.0,Biography|Drama|History,...,1000.0,6.4,2.35,18000,$13.00M,$29.96M,16959436.0,$16.96M,Biography,Drama
10,Color,Robert Altman,211.0,105.0,500.0,718.0,Virginia Madsen,11000.0,20338609.0,Comedy|Drama|Music,...,912.0,6.8,2.35,683,$10.00M,$20.34M,10338609.0,$10.34M,Comedy,Drama
11,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,14000.0,7.7,2.35,26000,$200.00M,$658.67M,458672302.0,$458.67M,Drama,Romance
12,Color,Baz Luhrmann,490.0,143.0,1000.0,77.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,509.0,7.3,2.35,115000,$105.00M,$144.81M,39812796.0,$39.81M,Drama,Romance
13,Color,Christopher Nolan,642.0,148.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,...,27000.0,8.8,2.35,175000,$160.00M,$292.57M,132568851.0,$132.57M,Action,Adventure
14,Color,Alejandro G. Iñárritu,556.0,156.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,...,27000.0,8.1,2.35,190000,$135.00M,$183.64M,48635922.0,$48.64M,Adventure,Drama
15,Black and White,Martin Scorsese,267.0,170.0,17000.0,827.0,Adam Scott,29000.0,102608827.0,Biography|Drama,...,3000.0,7.5,2.35,0,$110.00M,$102.61M,-7391173.0,$-7.39M,Biography,Drama
16,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,11000.0,8.5,2.35,199000,$100.00M,$162.80M,62804648.0,$62.80M,Drama,Western
17,Color,Edward Zwick,166.0,143.0,380.0,452.0,Djimon Hounsou,29000.0,57366262.0,Adventure|Drama|Thriller,...,3000.0,8.0,2.35,14000,$100.00M,$57.37M,-42633738.0,$-42.63M,Adventure,Drama
18,Color,Martin Scorsese,606.0,240.0,17000.0,4000.0,Matthew McConaughey,29000.0,116866727.0,Biography|Comedy|Crime|Drama,...,11000.0,8.2,2.35,138000,$100.00M,$116.87M,16866727.0,$16.87M,Biography,Comedy
19,Color,Martin Scorsese,233.0,216.0,17000.0,1000.0,Liam Neeson,29000.0,77679638.0,Crime|Drama,...,14000.0,7.5,2.35,0,$100.00M,$77.68M,-22320362.0,$-22.32M,Crime,Drama
20,Color,Martin Scorsese,352.0,151.0,17000.0,1000.0,Matt Damon,29000.0,132373442.0,Crime|Drama|Thriller,...,13000.0,8.5,2.35,29000,$90.00M,$132.37M,42373442.0,$42.37M,Crime,Drama
21,Color,Martin Scorsese,490.0,138.0,17000.0,163.0,Joseph Sikora,29000.0,127968405.0,Mystery|Thriller,...,223.0,8.1,2.35,53000,$80.00M,$127.97M,47968405.0,$47.97M,Mystery,Thriller
22,Color,Ridley Scott,238.0,128.0,0.0,135.0,Simon McBurney,29000.0,39380442.0,Action|Drama|Thriller,...,149.0,7.1,2.35,0,$70.00M,$39.38M,-30619558.0,$-30.62M,Action,Drama
23,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,15000.0,8.0,1.85,15000,$52.00M,$164.44M,112435221.0,$112.44M,Biography,Crime
24,Color,Danny Boyle,118.0,119.0,0.0,39.0,Virginie Ledoyen,29000.0,39778599.0,Adventure|Drama|Thriller,...,414.0,6.6,2.35,0,$50.00M,$39.78M,-10221401.0,$-10.22M,Adventure,Drama
25,Color,Sam Mendes,323.0,119.0,0.0,10000.0,Kate Winslet,29000.0,22877808.0,Drama|Romance,...,14000.0,7.3,2.35,0,$35.00M,$22.88M,-12122192.0,$-12.12M,Drama,Romance
26,Color,Randall Wallace,83.0,132.0,130.0,80.0,Anne Parillaud,29000.0,56876365.0,Action|Adventure,...,130.0,6.4,1.85,0,$35.00M,$56.88M,21876365.0,$21.88M,Action,Adventure
27,Color,Clint Eastwood,392.0,137.0,16000.0,363.0,Naomi Watts,29000.0,37304950.0,Biography|Crime|Drama,...,6000.0,6.6,2.35,16000,$35.00M,$37.30M,2304950.0,$2.30M,Biography,Crime
28,Black and White,Sam Raimi,63.0,107.0,0.0,159.0,Pat Hingle,29000.0,18636537.0,Action|Thriller|Western,...,165.0,6.4,1.85,0,$32.00M,$18.64M,-13363463.0,$-13.36M,Action,Thriller
29,Color,Jerry Zaks,45.0,98.0,4.0,11000.0,Robert De Niro,29000.0,12782508.0,Drama,...,22000.0,6.7,1.85,1000,$23.00M,$12.78M,-10217492.0,$-10.22M,Drama,Drama
30,Color,Baz Luhrmann,106.0,120.0,1000.0,954.0,Harold Perrineau,29000.0,46338728.0,Drama|Romance,...,1000.0,6.8,2.35,10000,$14.50M,$46.34M,31838728.0,$31.84M,Drama,Romance
31,Color,Baz Luhrmann,490.0,143.0,1000.0,76.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,509.0,7.3,2.35,115000,$105.00M,$144.81M,39812796.0,$39.81M,Drama,Romance
32,Color,David Fincher,362.0,166.0,21000.0,919.0,Jason Flemyng,11000.0,127490802.0,Drama|Fantasy|Romance,...,1000.0,7.8,2.35,23000,$150.00M,$127.49M,-22509198.0,$-22.51M,Drama,Fantasy
33,Color,Wolfgang Petersen,220.0,196.0,249.0,844.0,Orlando Bloom,11000.0,133228348.0,Adventure,...,5000.0,7.2,2.35,0,$175.00M,$133.23M,-41771652.0,$-41.77M,Adventure,Adventure
34,Color,Steven Soderbergh,198.0,125.0,0.0,350.0,Julia Roberts,11000.0,125531634.0,Crime|Thriller,...,8000.0,6.4,2.35,0,$110.00M,$125.53M,15531634.0,$15.53M,Crime,Thriller
35,Color,Doug Liman,233.0,126.0,218.0,322.0,Angelina Jolie Pitt,11000.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,...,11000.0,6.5,2.35,0,$120.00M,$186.34M,66336103.0,$66.34M,Action,Comedy
36,Color,Tony Scott,142.0,114.0,12000.0,307.0,Stephen Dillane,11000.0,26871.0,Action|Crime|Thriller,...,577.0,7.0,2.35,0,$92.00M,$0.03M,-91973129.0,$-91.97M,Action,Crime
37,Color,Steven Soderbergh,186.0,116.0,0.0,471.0,Bernie Mac,11000.0,183405771.0,Crime|Thriller,...,1000.0,7.8,2.35,0,$85.00M,$183.41M,98405771.0,$98.41M,Crime,Thriller
38,Color,David Ayer,406.0,134.0,452.0,697.0,Logan Lerman,11000.0,85707116.0,Action|Drama|War,...,8000.0,7.6,2.35,82000,$68.00M,$85.71M,17707116.0,$17.71M,Action,Drama
39,Color,Jean-Jacques Annaud,76.0,136.0,218.0,400.0,Mako,11000.0,37901509.0,Adventure|Biography|Drama|History|War,...,691.0,7.0,2.35,0,$70.00M,$37.90M,-32098491.0,$-32.10M,Adventure,Biography
40,Color,David Fincher,315.0,151.0,21000.0,637.0,Meat Loaf,11000.0,37023395.0,Drama,...,783.0,8.8,2.35,48000,$63.00M,$37.02M,-25976605.0,$-25.98M,Drama,Drama
41,Color,Patrick Gilmore,98.0,85.0,0.0,82.0,Adriano Giannini,11000.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,...,102.0,6.7,1.66,880,$60.00M,$26.29M,-33711680.0,$-33.71M,Adventure,Animation
42,Color,Neil Jordan,120.0,123.0,277.0,4000.0,Tom Cruise,11000.0,105264608.0,Drama|Fantasy|Horror,...,10000.0,7.6,1.85,11000,$60.00M,$105.26M,45264608.0,$45.26M,Drama,Fantasy
43,Color,Terrence Malick,584.0,139.0,0.0,687.0,Tye Sheridan,11000.0,13303319.0,Drama|Fantasy,...,1000.0,6.7,1.85,39000,$32.00M,$13.30M,-18696681.0,$-18.70M,Drama,Fantasy
44,Color,Andrew Dominik,273.0,160.0,181.0,820.0,Jeremy Renner,11000.0,3904982.0,Biography|Crime|Drama|History|Western,...,10000.0,7.5,2.35,0,$30.00M,$3.90M,-26095018.0,$-26.10M,Biography,Crime
45,Color,Alejandro G. Iñárritu,285.0,143.0,0.0,51.0,Harriet Walter,11000.0,34300771.0,Drama,...,119.0,7.5,1.85,0,$25.00M,$34.30M,9300771.0,$9.30M,Drama,Drama
46,Color,Angelina Jolie Pitt,131.0,122.0,11000.0,188.0,Angelina Jolie Pitt,11000.0,531009.0,Drama|Romance,...,11000.0,5.3,2.35,0,$10.00M,$0.53M,-9468991.0,$-9.47M,Drama,Romance
47,Color,Andrew Dominik,414.0,97.0,181.0,748.0,Sam Shepard,11000.0,14938570.0,Crime|Thriller,...,820.0,6.2,2.35,20000,$15.00M,$14.94M,-61430.0,$-0.06M,Crime,Thriller
48,Color,Tony Scott,122.0,121.0,12000.0,975.0,Gary Oldman,11000.0,12281500.0,Action|Crime|Drama|Romance|Thriller,...,10000.0,8.0,2.35,15000,$13.00M,$12.28M,-718500.0,$-0.72M,Action,Crime

In [59]:
# Write your code for grouping the combined dataframe here
group_combined = combined.groupby(['actor_1_name']).size().reset_index(name='count')
group_combined

        actor_1_name  count
0          Brad Pitt     17
1  Leonardo DiCaprio     21
2       Meryl Streep     11

In [77]:
# Write the code for finding the mean of critic reviews and audience reviews here
#meam_review['num_critic_for_reviews','num_user_for_reviews'] = combined['num_critic_for_reviews','num_user_for_reviews']
Meryl_Streep["mean"] = Meryl_Streep["num_critic_for_reviews"] + Meryl_Streep["num_user_for_reviews"]
Meryl_Streep["mean"].mean()

C:\Users\hP\AppData\Local\Temp\ipykernel_9188\10635089.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Meryl_Streep["mean"] = Meryl_Streep["num_critic_for_reviews"] + Meryl_Streep["num_user_for_reviews"]

478.6363636363636

In [78]:
Leo_Caprio["mean"] = Leo_Caprio["num_critic_for_reviews"] + combined["num_user_for_reviews"]
Leo_Caprio["mean"].mean()

C:\Users\hP\AppData\Local\Temp\ipykernel_9188\3640205779.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Leo_Caprio["mean"] = Leo_Caprio["num_critic_for_reviews"] + combined["num_user_for_reviews"]

559.0

In [79]:
Brad_Pitt["mean"] = Brad_Pitt["num_critic_for_reviews"] + Brad_Pitt["num_user_for_reviews"]
Brad_Pitt["mean"].mean()

C:\Users\hP\AppData\Local\Temp\ipykernel_9188\1407450658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Brad_Pitt["mean"] = Brad_Pitt["num_critic_for_reviews"] + Brad_Pitt["num_user_for_reviews"]

987.3529411764706

In [80]:
print("Brad Pitt has maximum mean out of three: ",Brad_Pitt["mean"].mean())

Brad Pitt has maximum mean out of three:  987.3529411764706